### PR TITLE
refactor(commands): convert to TS

### PR DESCRIPTION
**Pull request by Odyssey346**
This was basically just a rename of every js file in the commands folder to TS. Thank you PowerRename, very awesome tool.
Works on my machine. Atleast it should. Does #514

### CODE REVIEW

**Comment by Odyssey346** [comment]
@Rexogamer

**Review by Rexogamer — CHANGES_REQUESTED** [review]
Broken for some reason - the commands don't load upon startup (blocking review)

**Review by Rexogamer — APPROVED** [review]
update: it does, but it'd be nice to have a choice between ts and js

**Comment by Odyssey346** [comment]
I have a way of fixing that. I'll do it soon (if I don't, remind me to)

Den 3. april 2021 22:17:13 CEST, skrev Ed L ***@***.***>:
>@Rexogamer approved this pull request.
>
>update: it does, but it'd be nice to have a choice between ts and js
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/cytrus-re/cytrus-re/pull/515#pullrequestreview-627483817

-- 
Sendt fra min Android-enhet med K-9 e-post. Unnskyld min kortfattethet.

**Pull request closed without merging**
