### PR TITLE
fix(stuff): misc things i guess

### PR DESCRIPTION
**Pull request by Oxygemo**
Signed-off-by: Oxygemo/Odyssey346 :)

### CODE REVIEW

**Comment by Oxygemo** [comment]
why's the LGTM thing so slow?

**Comment by Oxygemo** [comment]
Rexo you fucking bastard you fucking retard I am going to report you to hacktoberfest for invalidating actual PRs

**Comment by Oxygemo** [comment]
rexo stop removing my comment uninvalidate the PR pls now you're just being a dick

**Comment by Oxygemo** [comment]
like srsly

**Comment by Rexogamer** [comment]
Please stop

**Comment by Oxygemo** [comment]
don't do that

**Comment by Oxygemo** [comment]
Can you remove the invalid tag please? Please stop acting like this. I want my points

**Comment by Rexogamer** [comment]
After all you've done, you don't deserve hacktober points for a PR *this* small, literally all you did was add a comment and change a couple log strings

**Comment by Oxygemo** [comment]
Let me do something big then, hold on

**Comment by Oxygemo** [comment]
I'm gonna fix an issue that's probably been plagueing you for long, if you invalidate this you're a cuck

**Comment by Oxygemo** [comment]
Cytrus-RE deleted a comment from Oxygemo

**Comment by Oxygemo** [comment]
image
I think it's gonna work outside of TTS now @Rexogamer

**Comment by CommandBlock6417** [comment]
well you forgot message.delete()

**Comment by Oxygemo** [comment]
well you're right

**Comment by Oxygemo** [comment]
ok no i just give up theres no point in contributing here anymore

**Pull request merged**
