### PR TITLE
Update and rename SECURITY.md to about-code-owners # These owners wil…

### PR DESCRIPTION
**Pull request by Ashkenazic**
…l be the default owners for everything in # the repo. Unless a later match takes precedence, they # will be requested for review when someone opens a PR.

### CODE REVIEW

**Comment by Rexogamer** [comment]
Spam PR, also who are you

**Comment by Oxygemo** [comment]
> pharmacy technician in Plymouth Meeting< PA

**Comment by Rexogamer** [comment]
not really that helpful in determining why he's here

**Comment by Oxygemo** [comment]
i know but its weird

**Comment by Oxygemo** [comment]
Also if I'm reading this correctly: You want full access to everything in the repository and be the owner for everything in this repo???? Sorry, we can't just give someone access to our repository and do whatever they want, especially when they didn't even do the changes.

**Comment by Oxygemo** [comment]
If you want to contribute code, go ahead and make a PR. Please nothing stupid though

**Pull request closed without merging**
