### PR TITLE
Revert "chore(npm-package): remoce odyssey"

### PR DESCRIPTION
**Pull request by Oxygemo**
This reverts commit 40b33c53680ab460c133039d0036b9f9fcff22da.

### CODE REVIEW

**Comment by QuantumlyTangled** [comment]
If anything you could remain in contributors but you are no longer a maintainer so thats wrong.

**Comment by Oxygemo** [comment]
I still can make PRs....

**Comment by Rexogamer** [comment]
By the NPM definition you are certainly a contributor, but not a maintainer

**Comment by Oxygemo** [comment]
yeah well let me commit that

**Comment by Oxygemo** [comment]
There, you can merge now. No excuses.

**Comment by Rexogamer** [comment]
just to shut you up

**Comment by Oxygemo** [comment]
fuck you man

**Comment by Oxygemo** [comment]
wait why's it report as closed?

**Comment by Rexogamer** [comment]
- gets what he wants
- "fuck off man"

If I were you, I would tone that attitude down

also technically merged PRs are considered closed

**Comment by Oxygemo** [comment]
I'm sorry. I misunderstood that you closed it

**Pull request merged**
