### PR TITLE
[Refactor] use yarn locking instead of npm

### PR DESCRIPTION
**Pull request by QuantumlyTangled**

### CODE REVIEW

**Review by Rexogamer — COMMENTED** [review]
Mostly LGTM, although you might want to update mathjs/eslint (although presumably Dependabot will recreate their PRs (#414/#413); also, seems a bit strange you removed yarn as opposed to pnpm in the scripts

**Comment by Oxygemo** [comment]
what's the advantage of doing this lol

**Comment by Oxygemo** [comment]
literally everyone uses NPM

**Comment by QuantumlyTangled** [comment]
> Mostly LGTM, although you might want to update mathjs/eslint (although presumably Dependabot will recreate their PRs (#414/#413); also, seems a bit strange you removed yarn as opposed to pnpm in the scripts

It seemed kinda weird to have a yarn script as in `npm run yarn` or `yarn yarn`. As for pnpm I didnt really fully grasp the `pnpm server` aspect of the command.

**Comment by QuantumlyTangled** [comment]
> literally everyone uses NPM

In this case because Dependabot and Depfu work better with yarn.lock files than package-lock.json files in terms of versioning. Plus it opens the path for the execution of .yarnclean files which lower the total install size of node_modules.
And the main reason I got the idea was because Rex expressed some sense of joy when the idea for this PR was brought up.

**Comment by Oxygemo** [comment]
I don't see

ons. 30. sep. 2020, 17:51 skrev QuantumlyTangled <notifications@github.com>:

**Pull request merged**
