### PR TITLE
Tsification

### PR DESCRIPTION
**Pull request by Odyssey346**

### CODE REVIEW

**Comment by Odyssey346** [comment]
about the command loader thing: the thing i tried didn't really work, i'll fix it later.

**Review by Rexogamer — CHANGES_REQUESTED** [review]
I... hate to be a pain but this will have to be rebased on bfb740a0a39904d13a17a2c439ccedee43d2b8cf

**Comment by Odyssey346** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by Odyssey346** [comment]
merge conflicts should be fixed

**Review by Rexogamer — APPROVED** [review]
lgtm, language chooser would be nice

**Comment by Odyssey346** [comment]
> 
> 
> lgtm, language chooser would be nice

i'll do this eventually

**Pull request merged**
