### PR TITLE
[Refactor] remove nodejs-base64

### PR DESCRIPTION
**Pull request by QuantumlyTangled**

### CODE REVIEW

**Comment by Oxygemo** [comment]
who the fuck are you?

**Comment by QuantumlyTangled** [comment]
> who the fuck are you?

Ok wow... that isn't a reply someone would expect from a maintainer. I am simply appalled.

**Comment by Oxygemo** [comment]
I am not a developer.

**Comment by QuantumlyTangled** [comment]
> I am not a developer.

The fact you are listed as an author contradicts that. Though I did hear you tend to be rather toxic.

**Comment by Oxygemo** [comment]
Well I did contribute massively, and was classified as someone who developed the not, but I no longer do. Yeah, I can be toxic, and I'm sorry. But my question still stands, who are you?

**Comment by QuantumlyTangled** [comment]
> Well I did contribute massively, and was classified as someone who developed the not, but I no longer do. Yeah, I can be toxic, and I'm sorry. But my question still stands, who are you? 

In all honesty I don't really care about behaviour just wanted to mess around. In any case Rex showed me the bot and asked if I wished to knock out put PRs in this jolly season.
If you wish to know my Discord handle it would be Q^2#0001.

**Comment by Oxygemo** [comment]
I see, thanks. I don't think he has been online at all today, this PR will probably be merged tomorrow or really late today

**Comment by Rexogamer** [comment]
Odyssey, knock it off, he's a pretty good dev + that's not how we talk to contributors

Q, LGTM

**Review by Rexogamer — APPROVED** [review]

**Comment by Oxygemo** [comment]
Rexo I said I was sorry to him. Please stop

**Comment by AdityaTD** [comment]
Remove this person as a maintainer \:) The man just said, "and was classified as someone who developed", which makes him no longer an active member to hold any sort of administrative powers over this project, especially with the behavior towards a person who made an actual well-written PR, unlike the recent ones I've seen from this "maintainer" for Hacktoberfest.

**Pull request merged**
