### PR TITLE
remove reply from addrole and use message.channel.send

### PR DESCRIPTION
**Pull request by Oxygemo**
pretty sure we're exterminating message.reply

### CODE REVIEW

**Comment by Oxygemo** [comment]
oh maybe i should've branched that change. oh well enjoy

**Comment by Oxygemo** [comment]
the portal 2 end credits song remind me of today's incident

**Review by Rexogamer — APPROVED** [review]

**Comment by Rexogamer** [comment]
shhh

**Comment by Oxygemo** [comment]
> shhh

;)

**Comment by Oxygemo** [comment]
seriously though, it does.

**Pull request merged**
