### PR TITLE
#525

### PR DESCRIPTION
**Pull request by Odyssey346**
this pushes changes from master into prod. i feel like it's time to update it.

*Please see #525 for more information*

### CODE REVIEW

**Comment by Odyssey346** [comment]
@Rexogamer stop doing whatever timewasting thing and review my pr

**Comment by Rexogamer** [comment]
- Stop being so desperate for reviews.
- Don't be so rude either.
- Prod will be pushed to soon for 1.4.1, probably tomorrow.

**Comment by Odyssey346** [comment]
how was i being rude? Also yeah last point is acceptable but I have to argue about them other points but GitHub isn't exactly the best place to start drama.

**Comment by Midou36O** [comment]
Closing the PR doesn't help at all, you just ruined a fix that is very important:
- Hard coding values is a bad practice and should be avoided
- While yes it isn't urgent, closing the PR literally means you don't want that bug fixed.

Reopening.

**Comment by Midou36O** [comment]
However i do agree pushing it to master directly sounds dumb and should be left till the 1.4.1

**Comment by Odyssey346** [comment]
Thank you Midou

**Comment by Rexogamer** [comment]
Please calm down and listen.
- Odyssey has repeatedly made rather demanding comments regarding reviewing his PRs. Wanting reviews is fine, but please have a bit of patience.
- These bug fixes, while nice, are not necessarily urgent and I'd rather wait and do the proper process instead of a random PR. Suggesting that closing *this* PR means I don't want this is frankly silly as I've... merged the changes into master.
- Re-opening a PR that has been closed for a specific reason is, frankly, ridiculous.

**Comment by Odyssey346** [comment]
> are not necessarily urgent
pfftttttt they're kinda urgent considering we had a major release and people are going to be wondering "why does this say 1.3?"

**Comment by Rexogamer** [comment]
We literally just released 1.4 and switched to the new system, how did you miss this?

**Comment by Odyssey346** [comment]
i meant for the info command.

**Comment by Rexogamer** [comment]
c.info was forgotten, I admit, but this is a pretty big PR with out of scope changes. I'm happy to merge the version commits, but please cherrypick those in a new PR.

**Comment by Odyssey346** [comment]
> In addition, I've always updated all mentions the hard coded version numbers upon a new release

well this time you forgot one. plus, we never make a new release

**Comment by Rexogamer** [comment]
Please read the above comment

**Comment by Odyssey346** [comment]
I have, i just didn't see it because I was typing and I'm on a phone.

**Comment by Midou36O** [comment]
Odyssey: don't be provocative please.

Rexo: 
> Odyssey has repeatedly made rather demanding comments regarding reviewing his PRs. Wanting reviews is fine, but please have a bit of patience.

I agree with you on this one. This can wait

> These bug fixes, while nice, are not necessarily urgent and I'd rather wait and do the proper process instead of a random PR. Suggesting that closing this PR means I don't want this is frankly silly as I've... merged the changes into master.

However here i don't agree with you, hard coding should still be considered as a low priority, but closing a PR sounds straight up like telling "i don't want this bug fixed."

> Re-opening a PR that has been closed for a specific reason is, frankly, ridiculous.

It isn't ridiculous, the specific reason is a good reason for it to be reopened.

**Comment by Odyssey346** [comment]
Although, can't you cherrypick those commits over yourself?

**Comment by Rexogamer** [comment]
Midou, please - if I didn't want the fixes why would they be merged into master?

**Comment by Baconz2** [comment]
your mother

**Comment by Rexogamer** [comment]
> Although, can't you cherrypick those commits over yourself?

I could, so I think it's best we end this PR here and I'll fix the linked issue tomorrow

**Comment by Odyssey346** [comment]
what the fuck

**Comment by MethodOrMadness** [comment]
unga bunga

**Comment by Baconz2** [comment]
your mother

**Comment by Midou36O** [comment]
Rexo mark this as off topic don't delete them :/

**Comment by Rexogamer** [comment]
**Please end this PR here.**

**Comment by Midou36O** [comment]
anyway please reopen this PR it's still a good PR, it just doesn't have to be merged right now~

**Comment by Rexogamer** [comment]
Midou, I literally just explained what I intend to do and why this PR isn't the correct way to do this.

**Comment by Midou36O** [comment]
**We'll keep this closed for now till tomorrow because i and rexo have to sleep.**

**Comment by Midou36O** [comment]
_**PR permanently closed.**_

**Reason**: This is already implemented in the master branch, it seems like i and odyssey wasn't very attentive actually, i apologize for the inconvenience.

**Pull request closed without merging**
