### PR TITLE
[Refactor]: package.json author field

### PR DESCRIPTION
**Pull request by QuantumlyTangled**

### CODE REVIEW

**Comment by CommandBlock6417** [comment]
CelestialCrafter is not really the author of this bot. We have changed it quite a lot.

**Comment by Oxygemo** [comment]
Can you change "Rexowogamer" to Rexogamer, and maybe add our discord tags & add my email (alej0hio2007@gmail.com)? Otherwise I like these changes.

**Comment by QuantumlyTangled** [comment]
> CelestialCrafter is not really the author of this bot. We have changed it quite a lot.

Would you like to list any other candidates? I really only chose them because they were first in the Author field string.

**Comment by Oxygemo** [comment]
Rexo & me I guess. I've contributed second best here.

**Comment by QuantumlyTangled** [comment]
> Can you change "Rexowogamer" to Rexogamer, and maybe add our discord tags & add my email ([alej0hio2007@gmail.com](mailto:alej0hio2007@gmail.com))? Otherwise I like these changes.

Sure I can add the email and change the name but I do ask where I should put the emails since I used npm-package standards, for the fields (name, email, url) which are the only accepted ones.

**Comment by QuantumlyTangled** [comment]
> Rexo & me I guess. I've contributed second best here.

Author is a single person field. So one or the other, but it can't be both.

**Comment by CommandBlock6417** [comment]
Then add Rexo as the author since he is the one who first forked the code.

**Comment by Oxygemo** [comment]
> > Can you change "Rexowogamer" to Rexogamer, and maybe add our discord tags & add my email ([alej0hio2007@gmail.com](mailto:alej0hio2007@gmail.com))? Otherwise I like these changes.
> 
> Sure I can add the email and change the name but I do ask where I should put the emails since I used npm-package standards, for the fields (name, email, url) which are the only accepted ones. 
How you put rexo and celest's emails and stuff ig.

**Comment by QuantumlyTangled** [comment]
> > > Can you change "Rexowogamer" to Rexogamer, and maybe add our discord tags & add my email ([alej0hio2007@gmail.com](mailto:alej0hio2007@gmail.com))? Otherwise I like these changes.
> > 
> > 
> > Sure I can add the email and change the name but I do ask where I should put the emails since I used npm-package standards, for the fields (name, email, url) which are the only accepted ones.
> 
> How you put rexo and celest's emails and stuff ig.

Oh... Seems like I made a typo, I meant the Discord tags. I apologize for the mistake.

**Comment by Oxygemo** [comment]
No need to apologize. We all make mistakes.

**Review by Rexogamer — CHANGES_REQUESTED** [review]
Mind adding @CommandBlock6417's email (if it's not public, I'll ask him about it)?

**Comment by QuantumlyTangled** [comment]
> Mind adding @CommandBlock6417's email (if it's not public, I'll ask him about it)?

I looked around their GH profile and some repos but couldn't find it. So please do if you don't mind.

**Comment by CommandBlock6417** [comment]
It's not public. It's pgkoutsoumanis@gmail.com

**Comment by Oxygemo** [comment]
Well now it's public.

**Comment by CommandBlock6417** [comment]
Well yes

**Comment by Oxygemo** [comment]
big brain

**Review by Rexogamer — APPROVED** [review]

**Pull request merged**
