### PR TITLE
refactor(version): global versioning

### LINKED ISSUE #520: 1.4.0 doesn't have link to new discord iirc
ig

### PR DESCRIPTION
**Pull request by Odyssey346**
Fixes #520 
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by Odyssey346** [comment]
lgtm

**Review by Rexogamer — APPROVED** [review]

**Comment by Rexogamer** [comment]
how does this fix #520

**Comment by Odyssey346** [comment]
look at the comments

**Comment by Rexogamer** [comment]
they aren't much help and looking at the PR's changes I only see version stuff

**Comment by Odyssey346** [comment]
what  i meant is that i will fix c.info's version

**Pull request merged**
